//filter  definition
export const GET_LISTDATA = 'GET_LISTDATA';
export const GET_LISTDATA_START = 'GET_LISTDATA_START';
export const SIGN_UP_STARTGET_LISTDATA_SUCCESS = 'GET_LISTDATA_SUCCESS';
export const GET_LISTDATA_FAILED = 'GET_LISTDATA_FAILED';

//sign up
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_UP_CLEAR = 'SIGN_UP_CLEAR';

//sign in
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_CLEAR = 'SIGN_IN_CLEAR';
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

//find password
export const FIND_PASSWORD = 'FIND_PASSWORD';
export const FIND_PASSWORD_START = 'FIND_PASSWORD_START';
export const FIND_PASSWORD_SUCCESS = 'FIND_PASSWORD_SUCCESS';
export const FIND_PASSWORD_FAILED = 'FIND_PASSWORD_FAILED';

//SNS Signin
export const SNS_SIGNIN = 'SNS_SIGNIN';
export const SNS_SIGNIN_CLEAR = 'SNS_SIGNIN_CLEAR';
export const SNS_SIGNIN_START = 'SNS_SIGNIN_START';
export const SNS_SIGNIN_SUCCESS = 'SNS_SIGNIN_SUCCESS';
export const SNS_SIGNIN_FAILED = 'SNS_SIGNIN_FAILED';

//generate access token
export const GENERATE_ACCESS_TOKEN = 'GENERATE_ACCESS_TOKEN';
export const GENERATE_ACCESS_TOKEN_START = 'GENERATE_ACCESS_TOKEN_START';
export const GENERATE_ACCESS_TOKEN_SUCCESS = 'GENERATE_ACCESS_TOKEN_SUCCESS';
export const GENERATE_ACCESS_TOKEN_FAILED = 'GENERATE_ACCESS_TOKEN_FAILED';

//live main
export const LIVE_MAIN_GET = 'LIVE_MAIN_GET';
export const LIVE_MAIN_START = 'LIVE_MAIN_START';
export const LIVE_MAIN_SUCCESS = 'LIVE_MAIN_SUCCESS';
export const LIVE_MAIN_FAILED = 'LIVE_MAIN_FAILED';

//notice
export const NOTICE_GET = 'NOTICE_GET';
export const NOTICE_CLEAR = 'NOTICE_CLEAR';
export const NOTICE_START = 'NOTICE_START';
export const NOTICE_SUCCESS = 'NOTICE_SUCCESS';
export const NOTICE_FAILED = 'NOTICE_FAILED';

//list review (replay)
export const REPLAY_GET = 'REPLAY_GET';
export const REPLAY_CLEAR = 'REPLAY_CLEAR';
export const REPLAY_START = 'REPLAY_START';
export const REPLAY_SUCCESS = 'REPLAY_SUCCESS';
export const REPLAY_FAILED = 'REPLAY_FAILED';

//live detail
export const DETAIL_GET = 'DETAIL_GET';
export const DETAIL_CLEAR = 'DETAIL_CLEAR';
export const DETAIL_START = 'DETAIL_START';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';
export const DETAIL_FAILED = 'DETAIL_FAILED';

//my page change password
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_CLEAR = 'CHANGE_PASSWORD_CLEAR';
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

//get me
export const GET_ME = 'GET_ME';
export const GET_ME_CLEAR = 'GET_ME_CLEAR';
export const GET_ME_START = 'GET_ME_START';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILED = 'GET_ME_FAILED';

//update profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_CLEAR = 'UPDATE_PROFILE_CLEAR';
export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

//update image profile
export const UPDATE_IMAGE_PROFILE = 'UPDATE_IMAGE_PROFILE';
export const UPDATE_IMAGE_PROFILE_START = 'UPDATE_IMAGE_PROFILE_START';
export const UPDATE_IMAGE_PROFILE_SUCCESS = 'UPDATE_IMAGE_PROFILE_SUCCESS';
export const UPDATE_IMAGE_PROFILE_FAILED = 'UPDATE_IMAGE_PROFILE_FAILED';

//delete account
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_START = 'DELETE_ACCOUNT_START';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';

//poke channel
export const POKE_CHANNEL = 'POKE_CHANNEL';
export const POKE_CHANNEL_CLEAR = 'POKE_CHANNEL_CLEAR';
export const POKE_CHANNEL_START = 'POKE_CHANNEL_START';
export const POKE_CHANNEL_SUCCESS = 'POKE_CHANNEL_SUCCESS';
export const POKE_CHANNEL_FAILED = 'POKE_CHANNEL_FAILED';

//poke list
export const POKE_LIST_GET = 'POKE_LIST_GET';
export const POKE_LIST_CLEAR = 'POKE_LIST_CLEAR';
export const POKE_LIST_START = 'POKE_LIST_START';
export const POKE_LIST_SUCCESS = 'POKE_LIST_SUCCESS';
export const POKE_LIST_FAILED = 'POKE_LIST_FAILED';

//channel list
export const CHANNEL_LIST_GET = 'CHANNEL_LIST_GET';
export const CHANNEL_LIST_CLEAR = 'CHANNEL_LIST_CLEAR';
export const CHANNEL_LIST_START = 'CHANNEL_LIST_START';
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS';
export const CHANNEL_LIST_FAILED = 'CHANNEL_LIST_FAILED';

//channel detail
export const CHANNEL_DETAIL_GET = 'CHANNEL_DETAIL_GET';
export const CHANNEL_DETAIL_CLEAR = 'CHANNEL_DETAIL_CLEAR';
export const CHANNEL_DETAIL_START = 'CHANNEL_DETAIL_START';
export const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
export const CHANNEL_DETAIL_FAILED = 'CHANNEL_DETAIL_FAILED';

//poke channel2 => before is poke program but client call it is channel
export const POKE_CHANNEL_2 = 'POKE_CHANNEL_2';
export const POKE_CHANNEL_CLEAR_2 = 'POKE_CHANNEL_CLEAR_2';
export const POKE_CHANNEL_START_2 = 'POKE_CHANNEL_START_2';
export const POKE_CHANNEL_SUCCESS_2 = 'POKE_CHANNEL_SUCCESS_2';
export const POKE_CHANNEL_FAILED_2 = 'POKE_CHANNEL_FAILED_2';

//update push alert status
export const UPDATE_PUSH_ALERT = 'UPDATE_PUSH_ALERT';
