import { StyleSheet, Dimensions } from 'react-native';
import Config from '../../config';

export const styles = StyleSheet.create({
  loadingContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentContainer: {
    backgroundColor: '#FDF9ED',
  },
  container: {},
  iconMyPageContainer: {
    backgroundColor: 'white',
    width: 54,
    height: 54,
    borderRadius: 27,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 15,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  iconMyPage: {
    width: 54,
    height: 54,
    resizeMode: 'contain',
  },
  headerAreae: {
    display: 'flex',
    flexDirection: 'row',
    paddingHorizontal: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 20,
  },
  headerTabWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tabContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: 53,
  },
  alarmIconContainer: {
    // backgroundColor: '#FFEDED',
    width: 54,
    height: 54,
    // borderRadius: 27,
    // display: 'flex',
    // justifyContent: 'center',
    // alignItems: 'center',
    // elevation: 15,
    // shadowOffset: {width: 0, height: 0},
    // shadowColor: 'rgba(0, 0, 0, 0.1)',
    // shadowOpacity: 0.5,
    // shadowRadius: 10,
  },
  alarmIcon: {
    width: 54,
    height: 54,
    resizeMode: 'contain',
  },
  programContent: {
    flex: 1,
  },
  slideViewContainer: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  contentContainerCustomStyle: {
    alignItems: 'center',
  },
  carouselItemContainer: {
    overflow: 'hidden',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  carouselItemBackground: {
    overflow: 'hidden',
    justifyContent: 'space-between',
    paddingVertical: 0,
    paddingLeft: 0,
  },
  channelContentContainer: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: 15,
    alignItems: 'center',
  },
  channelItemContaimner: {
    marginRight: 15,
  },
  channelLogo: {
    borderRadius: 70,
  },
  channelName: {
    textAlign: 'center',
    color: '#141414',
    fontSize: 13,
    marginTop: 10,
  },
  playAloneContentContainer: {
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollTitle: {
    color: '#111111',
    fontSize: 17,
    marginLeft: 15,
    marginTop: 5,
    height: 20,
    position: 'absolute',
    top: 5,
  },
  modalContainer: {
    backgroundColor: 'transparent',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  modalWrapper: {
    width: 300,
    height: 200,
    backgroundColor: 'white',
    borderRadius: 10,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    color: '#222222',
    fontSize: 18,
    paddingHorizontal: 50,
    paddingTop: 50,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  modalChoiceWrapper: {
    width: 300,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButtonCancel: {
    backgroundColor: '#9A9A9A',
    width: 120,
    height: 45,
    display: 'flex',
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginLeft: 20,
  },
  modalButtonCancelTitle: {
    color: 'white',
    fontSize: 17,
  },
  modalButtonConfirm: {
    backgroundColor: '#50CCC3',
    width: 120,
    height: 45,
    display: 'flex',
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginRight: 20,
  },
  modalButtonConfirmTitle: {
    color: 'white',
    fontSize: 17,
  },
  onAirBackgroundImage: {
    alignSelf: 'flex-end',
    marginBottom: -20,
  },
  scheduleItemWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scheduleItemContainer: {
    borderRadius: 10,
    flexDirection: 'column',
    padding: 30,
    backgroundColor: 'white',
    paddingHorizontal: 25,
    elevation: 15,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  scheduleItemInforWrapper: {
    flex: 1,
    flexDirection: 'row',
  },
  scheduleItemImageContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  scheduleItemImage: {
    width: '100%',
    height: '90%',
    borderRadius: 10,
  },
  scheduleDetailWrapper: {
    flex: 2,
    justifyContent: 'space-around',
    paddingLeft: 15,
  },
  scheduleItemTimeContainer: {
    backgroundColor: '#74DC9D',
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    paddingHorizontal: 20,
    paddingVertical: 5,
  },
  scheduleItemTime: {
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
  },
  liveItemTimeWrapper: {
    flexDirection: 'row',
    paddingLeft: 15,
    paddingTop: 10,
  },
  liveItemTimeContainer: {
    flexDirection: 'row',
    borderRadius: 10,
    overflow: 'hidden',
  },
  liveStatusContainer: {
    backgroundColor: '#F7543F',
    paddingHorizontal: 10,
    paddingVertical: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  liveStatus: {
    fontSize: 16,
    color: 'white',
  },
  liveTimeContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 10,
  },
  liveTime: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  liveCategory: {
    fontSize: 12,
    color: 'white',
    fontWeight: 'bold',
  },
  liveTitle: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
  },
  playBtnContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'rgba(0,0,0,0.25)',
  },
  loadingIconContainer: {
    width: 500,
    height: 100,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataText: {
    fontSize: 16,
    color: 'rgba(0,0,0,0.4)',
  },
});
